import test from 'node:test'
import assert from 'node:assert/strict'
import { buildChecklist, shipmentStatus, shipmentTotal, validateShipment } from './logic.js'

const data={exporter:{companyName:'A'},buyer:{companyName:'B'},shipment:{destinationCountry:'Singapore',mode:'Air',preferentialTariff:true,productCategory:'Food'},products:[{name:'Coffee',quantity:10,unitPrice:5,cartonCount:2,grossWeight:8,hsCode:''}]}
const ready={exporter:{companyName:'A',registrationNumber:'1',address:'MY',contactPerson:'A',email:'a@example.com'},buyer:{companyName:'B',address:'SG',contactPerson:'B',email:'b@example.com'},shipment:{originCountry:'Malaysia',destinationCountry:'Singapore',mode:'Air',incoterm:'FOB',currency:'USD',departureDate:'2026-08-01',arrivalDate:'2026-08-02',preferentialTariff:true,productCategory:'Food',customsRestrictionChecked:true,customsDeclarationStatus:'Filed / accepted',transportDocumentStatus:'Issued',strategicGoods:'No',originQualified:true,originDocumentStatus:'Issued',maqisStatus:'Obtained'},products:[{name:'Coffee',description:'Roasted coffee',quantity:10,unitPrice:5,cartonCount:2,netWeight:7,grossWeight:8,hsCode:'0901.21'}]}
test('totals calculate quantity times unit price',()=>assert.equal(shipmentTotal(data),50))
test('air, tariff and food conditions update checklist',()=>{const c=buildChecklist(data);assert.equal(c.items.find(x=>x.name==='Air Waybill').status,'Needs Info');assert.equal(c.items.find(x=>x.name==='Bill of Lading').status,'Not Applicable');assert.equal(c.items.find(x=>x.name==='ATIGA Origin Evidence').required,true);assert.match(c.warning,/HS code/)})
test('validation reports incomplete shipment details',()=>assert.ok(validateShipment(data).includes('exporter.registrationNumber')))
test('status stays needs info while carrier documents are outstanding',()=>assert.equal(shipmentStatus(data),'Needs info'))
test('official rules become ready only after regulatory confirmations',()=>{const c=buildChecklist(ready);assert.equal(c.items.find(x=>x.name==='Customs Export Declaration (K2)').status,'Ready');assert.equal(c.items.find(x=>x.name==='ATIGA Origin Evidence').status,'Ready');assert.equal(c.items.find(x=>x.name==='MAQIS Permit / Inspection Verification').status,'Ready');assert.equal(shipmentStatus(ready),'Ready')})
test('draft external documents never count as ready',()=>{const draft=structuredClone(ready);draft.shipment.customsDeclarationStatus='Filed / awaiting acceptance';draft.shipment.transportDocumentStatus='Draft received';draft.shipment.originDocumentStatus='Applied';const c=buildChecklist(draft);assert.equal(c.items.find(x=>x.name==='Customs Export Declaration (K2)').status,'Needs Info');assert.equal(c.items.find(x=>x.name==='Air Waybill').status,'Needs Info');assert.equal(c.items.find(x=>x.name==='ATIGA Origin Evidence').status,'Needs Info')})
test('strategic goods require an obtained MITI permit',()=>{const held=structuredClone(ready);held.shipment.strategicGoods='Yes';held.shipment.staPermitStatus='Applied';assert.equal(buildChecklist(held).items.find(x=>x.name==='Strategic Trade Act Screening / Permit').status,'Needs Info');held.shipment.staPermitStatus='Obtained';assert.equal(buildChecklist(held).items.find(x=>x.name==='Strategic Trade Act Screening / Permit').status,'Ready')})
